### ISSUE TITLE
Meson build fail - can't find libevent_pthreads

### ISSUE THREAD

**Issue by paullee2018** [kbingham/simple-cam#2]
Hi,

I am trying to build the example and get the following error.

`Run-time dependency libevent_pthreads found: NO (tried pkgconfig and cmake)

../meson.build:16:0: ERROR: Dependency "libevent_pthreads" not found, tried pkgconfig and cmake

A full log can be found at /home/pi/projects/simple-cam/_build/meson-logs/meson-log.txt
`
I have installed libevent-pthreads-2.1-6 in the raspberry PI but unable to link this library.

Any ides?

Paul

**Comment by lisosia** [comment]
@paullee2018  try this before build
```
sudo apt install libevent-dev
```

**Comment by kbingham** [comment]
Sorry - just saw this on the notification.

Yes, perhaps we should add some package requirements to a readme to make it easier.

**Comment by paullee2018** [comment]
> sudo apt install libevent-dev

Cool that worked. Thanks
