### ISSUE TITLE
scan out frame example

### ISSUE THREAD

**Issue by Scott31393** [kbingham/simple-cam#3]
Hi Kieran,
Thanks for sharing. Can you suggest how to scan out some frame of the camera in a window for example.
I think the valid place to do this, like you suggest, can be here:

https://github.com/kbingham/simple-cam/blob/bb97f3bbd96a9d347e1b7f6cb68d94efaf8db574/simple-cam.cpp#L104

Thanks in advance! :)

**Comment by kbingham** [comment]
Hi 

It depends a lot on your use cases from that point. You could use QT, GTK, SDL or direct rendering to the screen with DRM.

There's an example addition to cam which allows outputting to a window with SDL which might be easily followed:

https://git.libcamera.org/libcamera/libcamera.git/commit/?id=11554a259f4e8df3cc2ddce0217d35fd7797cfc5

Cam and qcam have more features, but aren't always easier to follow.

It could be tempting to add SDL support to simple-cam, but I want to try to keep it as minimal as possible as an example of the main interfaces. But displaying is probably useful as part of that ;-)

**Comment by Scott31393** [comment]
Really Thanks!

Update:
Forgot to post a valid starting point: :)
https://github.com/Scott31393/libcamera/blob/master/Documentation/guides/application-developer.rst
